### ISSUE TITLE
ide panel - Resizing side panel should resize the simulator

### ISSUE THREAD

**Issue by terrysahaidak** [software-mansion/react-native-ide#133]
When using side panel, the simulator is just huge. Would be cool to be able to change its size. But also it should automatically scale by accessible width on resizing

Here is an example:

https://github.com/software-mansion/react-native-ide/assets/7809008/933ea2cf-e641-4ab5-88d9-021295943143

**Comment by jakub-gonet** [comment]
Seems like zoom feature solved that.
