### ISSUE TITLE
Failed to build iOS app on expo

### ISSUE THREAD

**Issue by dmaykov** [software-mansion/react-native-ide#134]
Hey team, thanks for adding me to the beta release!

I tried to use the extension with monorepo, but there build failure of iOS app. We use expo@~50.0.11. Find build logs in the attachment.

Do you know what could be the issue?
[logs.txt](https://github.com/software-mansion/react-native-ide/files/15083824/logs.txt)

**Comment by jakub-gonet** [comment]
This issue was not active for some time so I'm closing it.
If you need further help please reply or create a new issue.
