### ISSUE TITLE
Cannot run project

### ISSUE THREAD

**Issue by Brunowilliang** [software-mansion/react-native-ide#193]
Hi guys, can anyone help me with this error? I installed everything correctly and ran the IDE, but it doesn't get rid of this error

![CleanShot 2024-05-02 at 12 20 41@2x](https://github.com/software-mansion/react-native-ide/assets/41432581/634aa2a5-8bfe-44c0-8cfe-02afad3ecae6)

**Comment by jakub-gonet** [comment]
This issue was not active for some time so I'm closing it.
If you need further help please reply or create a new issue.
