### ISSUE TITLE
Element inspector doesn't work in RN 74

### ISSUE THREAD

**Issue by kmagiera** [software-mansion/react-native-ide#240]
This issue is to track progress on fixes necessary to get element inspector workable again after update to 0.74

The reason behind the breakage is this PR from react that removes debugSource from fiber nodes: https://github.com/facebook/react/pull/28265

Despite this change not being included in any react release, it's already included in the renderer code in RN 74 and Expo 51.

**Comment by pietgk** [comment]
i have a working inspector in a RN 0.74.2 project....

**Comment by kmagiera** [comment]
ah, this got fixed some time ago, the issue should be closed now. Thanks
