### ISSUE TITLE
Breakpoints don't work + can't configure launch.json

### ISSUE THREAD

**Issue by nmalzieu** [software-mansion/react-native-ide#253]
If I set breakpoints, they don't work. I tried adding a breakpoint to a button click and when I click on the button nothing happens in VSCode.
I had no launch.json, so I tried adding one and running "Run and Debug" using "React Native IDE panel" but I have the following error:
![Capture d’écran 2024-05-14 à 10 54 34](https://github.com/software-mansion/react-native-ide/assets/2102342/f447f02e-1fa7-4725-aa12-0694c35abbac)

Here is the content of my launch.json file:

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "react-native-ide",
            "request": "launch",
            "name": "React Native IDE panel",
            "ios": {
                "configuration": "Debug"
            },
            "android": {
                "variant": "debug"
            }
        }
    ]
}
```

Apart from that I can run the app in the panel and other stuff works like clicking on an element and opening the resulting code.

**Environment**
- Version of currently used React Native IDE : v0.0.10-beta
- Version of React Native/Expo used in the project: Expo 50.0.17, RN 0.73.6
- Any other versions of tools related to the problem: VSCode 1.89.1 (Universal)

**Comment by glockjt** [comment]
Is there an update on this? Breakpoints are not working for me as well

**Comment by jakub-gonet** [comment]
@glockjt Can you please provide information about libraries' versions used in your project?

**Comment by jakub-gonet** [comment]
This issue was not active for some time so I'm closing it.
If you need further help please reply or create a new issue.
