### ISSUE TITLE
Preview not showing when i click on open IDE and it shows error

### ISSUE THREAD

**Issue by Talhaverse** [software-mansion/react-native-ide#290]
Error loading webview: Error: Could not register service worker: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..

**Environment**
"dependencies": {
    "@expo/vector-icons": "^14.0.0",
    "@react-navigation/native": "^6.0.2",
    "expo": "~51.0.8",
    "expo-constants": "~16.0.1",
    "expo-font": "~12.0.5",
    "expo-linking": "~6.3.1",
    "expo-router": "~3.5.14",
    "expo-splash-screen": "~0.27.4",
    "expo-status-bar": "~1.12.1",
    "expo-system-ui": "~3.0.4",
    "expo-web-browser": "~13.0.3",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.74.1",
    "react-native-gesture-handler": "~2.16.1",
    "react-native-reanimated": "~3.10.1",
    "react-native-safe-area-context": "4.10.1",
    "react-native-screens": "3.31.1",
    "react-native-web": "~0.19.10"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@types/jest": "^29.5.12",
    "@types/react": "~18.2.45",
    "@types/react-test-renderer": "^18.0.7",
    "jest": "^29.2.1",
    "jest-expo": "~51.0.2",
    "react-test-renderer": "18.2.0",
    "typescript": "~5.3.3"
  },
  "private": true
}

**Comment by exondus** [comment]
I had the same error but I realised that I had launched vscode from inside the project directory which includes other apps but it worked when I opened it specifically inside the Expo directory. Hope this helps.

**Comment by Talhaverse** [comment]
Can you please explain this in more detail , I opened the project by typing code. in the command prompt , please describe so I try and update thanks

**Comment by exondus** [comment]
It sounds like your situation is different from mine. I have a root directory with 3 apps, the Expo app is one of them, so the mistake I made was to open vscode inside the root directory instead of what it says in the docs: open your React Native of Expo project as workspace in vscode (File > Open Folder... option or using code command with the folder name from terminal).

**Comment by Talhaverse** [comment]
Ohh I see let me check and try again

**Comment by Talhaverse** [comment]
It's solved, just close vscode kill all windows and reopen
