### ISSUE TITLE
Command 'React Native IDE: Diagnostics' resulted in an error

### ISSUE THREAD

**Issue by MariuzM** [software-mansion/react-native-ide#296]
Having issue starting React Native IDE on my VSCode, i have my vscode setup as portable not sure if thats the issue

<img width="608" alt="image" src="https://github.com/software-mansion/react-native-ide/assets/36937039/690e6994-5b2b-4e4c-87a8-171b6de52477">

<img width="689" alt="image" src="https://github.com/software-mansion/react-native-ide/assets/36937039/947a7e1b-3be9-4644-af25-db972c47762a">

**Comment by radko93** [comment]
I have the same, with regular setup.

**Comment by tokkozhin** [comment]
I have the same error with portable vscode and monorepo project

**Comment by jakub-gonet** [comment]
Does the VSCode show an error when you uninstall and install RN IDE again?

**Comment by dynamichny** [comment]
@jakub-gonet yes, I tried to reinstall the extension multiple times, but the result is always the same

**Comment by radko93** [comment]
I got this one during launch:
```
mainThreadExtensionService.ts:113 Activating extension 'swmansion.react-native-ide' failed: Error: ENOENT: no such file or directory, stat '/Users/radko93/.vscode/extensions/swmansion.react-native-ide-0.0.14-darwin-arm64/dist/sim-server'.
```

**Comment by rothfels** [comment]
I also ran into this. I was able to resolve by uninstalling the extension via `rm -rf` from `~/.vscode/extensions`, then reinstalling. Doing uninstall / reinstall via the vscode extensions UI didn't work.

**Comment by radko93** [comment]
Ok I did remove the extension as above, reinstall and it's there!

**Comment by MariuzM** [comment]
For me this still is a problem even if manually removing extension

**Comment by MariuzM** [comment]
I think i found issue, maybe, i have noticed that in my standalone project https://github.com/MariuzM/expo-starter like this its working now, but in some projects i have kinda like monorepo setup where in root folders for mobile, server and web, and for example in mobile folder it has my project.

If i start vscode from the root with all those folders then IDE does not work
If i open mobile folder in vscode then it works

**Comment by jakub-gonet** [comment]
Are you able to share the project (with stripped out logic, we're only interested in configs) or to share directory structure and configs?

`sim-server` error should be independent bug, we changed how it's installed recently and it shouldn't be a problem anymore.

**Comment by MariuzM** [comment]
@jakub-gonet here is same project but moved to `client_mobile` folder
https://github.com/MariuzM/expo-starter/tree/test-react-native-ide

Start VSCode in the Root structure of the project so you should see 
![image](https://github.com/software-mansion/react-native-ide/assets/36937039/a5b2d390-c7a4-4922-b241-b8a12eabfe43)

When project starts with project code being in folder then IDE is not being detected. I guess IDE only works when project code is in the ROOT and not in folders.

**Comment by jakub-gonet** [comment]
Have you tried using `appRoot` config option?

https://ide.swmansion.com/docs/configuration#other-settings

**Comment by MariuzM** [comment]
Thank you i think its working kinda now, I'm getting some build issues but i will post another ticket for this different case.

**Comment by jadeye** [comment]
Nothing helps.....I have an android/ react-native and I tried all tht is suggested...Nothing worx!
