### ISSUE TITLE
Took to ong and still doesnt open as it should 

### ISSUE THREAD

**Issue by ArdianOSM** [software-mansion/react-native-ide#300]
**Description*

**Environment**
- Version of currently used React Native IDE (Extensions tab -> click on React Native IDE extension -> version is located next to the extension name)
- Version of React Native/Expo used in the project.
- Any other versions of tools related to the problem.

**Comment by jakub-gonet** [comment]
This issue is insufficiently described. Please add versions of your dependencies, describe what's exactly happening and attach relevant logs.
