### ISSUE TITLE
[Custom Metro Config] expo-start.js script fails for Bare React Native project

### ISSUE THREAD

**Issue by tr3v3r** [software-mansion/react-native-ide#318]
**Description**
Trying to run Bare React Native project with installed expo SDK ( we use expo-image) and see the following build issue:

<img width="1147" alt="image" src="https://github.com/software-mansion/react-native-ide/assets/23724142/e4f0eb0d-9e76-47e5-b393-8c31151d0d4c">

<br/><br/>

**Important details**
What's important is that we're using a nonstandard metro config for development. 
It looks similar to this - https://github.com/tr3v3r/react-native-esc-pos-printer/blob/main/example/metro.config.js. 
It was generated by react-native-builder-bob.

P.s. For normal metro.config -  all good.
<br/><br/>
**Findings**
So as I understood expo-start cannot process such types of metro configs, but from my understanding, it should not **even run** for bare projects.

And I think it runs because of this:

<img width="708" alt="image" src="https://github.com/software-mansion/react-native-ide/assets/23724142/6b3c9d43-e5b0-4477-8c59-613f9911d9ec">

<br/><br/>
**Conclusion**

Maybe **shouldUseExpoCLI** should rely on something more than checking if expo SDK exists and not start expo-start.js script for bare projects, even if some expo packages are installed.

<br/><br/>
**Environment**

IDE version: **0.0.14**
react-native: **0.72.3 (bare + expo-image)**
platforms: iOS / Android

**Comment by kmagiera** [comment]
This check doesn't test for Expo SDK but for Expo CLI. I don't know of a better way to automatically tell whether project is Expo or React Native based. Do you have any suggestions? Expo CLI is not needed and shouldn't be installed along with expo SDK. Is this what you're seeing?
