### ISSUE TITLE
can't use gps sensor in android emulator

### ISSUE THREAD

**Issue by babpulss** [software-mansion/react-native-ide#330]
Hi, thanks to your effort in this project
I'm impressed 
and this is what I met error in IDE emulator

Error: Call to function 'ExpoLocation.startLocationUpdatesAsync' has been rejected.
**Environment**

    "expo": "~50.0.19",
    "expo-location": "^16.5.5",

and I did in app.json

      [
        "expo-location",
        {
          "isAndroidBackgroundLocationEnabled": true,
          "isAndroidForegroundServiceEnabled": true,
          "isIosBackgroundLocationEnabled": true
        }
      ],

p.s. work fine in typical android emuator

**Comment by filip131311** [comment]
Hello thank you for your feedback, unfortunately current version of IDE does not support setting devices location, but we are working on it in #317 ;).
