### ISSUE TITLE
"Fit" option in zoom panel only fits in vertical

### ISSUE THREAD

**Issue by Stenbaek** [software-mansion/react-native-ide#334]
**Description**
Choosing the "Fit" Option in the RN IDE only seems to fit in the vertical space, but will overflow the width of the window. I expected the Fit option to fit to the maximum size where the whole simulator would be visible.

**Environment**
- Version of currently used React Native IDE: 0.0.14

https://github.com/software-mansion/react-native-ide/assets/624812/4f2b7d89-0d4f-4e52-af84-1d38070d1ae8

**Comment by filip131311** [comment]
fixed by #363
