### ISSUE TITLE
Couldn't start device session Command was killed with SIGABRT (Aborted)

### ISSUE THREAD

**Issue by acouvreur1997** [software-mansion/react-native-ide#339]
**Description**
I'm trying to launch an application with expo 50 with React Native IDE 0.0.14 on iOS with iPhone 15 Pro (i have Xcode 15.3 and on Locations Settings i have Xcode15 15.3 on Command Line Tools).

The iOS build with React Native IDE is successful but i get the error on the React Native IDE logs :
"Couldn't start device session Command was killed with SIGABRT (Aborted): .vscode/extensions/swmansion.react-native-ide-0.0.14-darwin-arm64/dist/sim-server ios F3FC0BEC-BF9F-490F-84E9-625619544522 Library/Caches/com.swmansion.react-native-ide/Devices/iOS". 

I tried to run the project on the iPhone 15 Pro simulator directly on Xcode and it works.

Do you have any ideas to resolve this problem ?

**Environment**
- Version of currently used React Native IDE : 0.0.14
- Version of React Native/Expo used in the project : expo 50.0.14
- Xcode 15.3 / Simulator iPhone 15 Pro (iOS 17.4)

**Comment by acouvreur1997** [comment]
My output of xcode-select -p is : /Desktop/Xcode15.3/Xcode15.3.app/Contents/Developer
I need to have 2 versions of Xcode on my mac so i don't use the Xcode on AppStore, i downloaded specific versions on https://xcodereleases.com/.
There is a way to tell the ide the specific path of xcode-select -p ?

**Comment by jakub-gonet** [comment]
Not yet, we're working on it. For the time being you can try symlinking it to this location and checking if it works.

**Comment by acouvreur1997** [comment]
Thanks you 😄 , with the symlink, the simulator launches correctly on the ide extension

**Comment by jakub-gonet** [comment]
@acouvreur1997 in the next release you can probably delete the symlink, we'll handle it automatically. 
https://github.com/software-mansion/react-native-ide/pull/364

We plan to release new version every few weeks.
