### ISSUE TITLE
Choose how to run the app.

### ISSUE THREAD

**Issue by kzlar** [software-mansion/react-native-ide#343]
**Description**
From what I can tell, React Native IDE always re-build the app (aka `npx expo run:ios`), while that would always work, it takes significantly more time than just running the js side (aka `npx expo start --ios`).
Would be great if there was a way to choose how I'd like the app to run (default to `expo start` but allow to occasionally selection `expo run:ios` in case my native dependencies have changes).

**Environment**
v0.0.10
Expo SDK 51

**Comment by kmagiera** [comment]
The reason why the IDE runs the build is that it also calculates the build fingerprint, which represents the native dependencies that when changed should require rebuilding the app. So in typical scenarios the app would only build once, and then occasionally when native dependencies change (i.e. you change branch with different dependencies or modify native sources). 

We do plan to work on some alternative workflow where you could choose to use builds that are done elsewhere (specifically for use cases where people have custom expo dev-client-like setups and build native shell outside of the developers' machines), but I believe that the current version should work best in majority of the setups.

If the app is rebuilding too often and not only when native deps change, that's a bug and if that's what you're observing please share more details such that we can investigate.

**Comment by kzlar** [comment]
Thank you!
