### ISSUE TITLE
Started correctly but no features work

### ISSUE THREAD

**Issue by Albert-Gao** [software-mansion/react-native-ide#346]
**Description*
I pressed the "Open IDE Panel" button, it opens the iOS simulator and started the project, all fine, but none of the features works like, inspect-go-to-file, stop-at-break-point.

I also tried to started the app from the debug panel using the default config, same outcome

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "react-native-ide",
            "request": "launch",
            "name": "React Native IDE panel",
            "ios": {
                "configuration": "Debug"
            },
            "android": {
                "buildType": "debug"
            }
        }
    ]
}
```

**Environment**
    "expo": "~51.0.9",
    "react-native": "0.74.1",

![image](https://github.com/software-mansion/react-native-ide/assets/18282328/1e7f24b2-7dab-4ab1-a6ac-130a0d900191)

**Comment by jakub-gonet** [comment]
It should work out of the box. Can you share the project reproducing the issue?

**Comment by jakub-gonet** [comment]
This issue was not active for some time so I'm closing it.
If you need further help please reply or create a new issue.

**Comment by Albert-Gao** [comment]
sorry, i can confirm it has been fixed in the latest version :)
