### ISSUE TITLE
Create IOS Devices first time start

### ISSUE THREAD

**Issue by justdan0227** [software-mansion/react-native-ide#356]
Mac M3Pro Sonoma 14.5

Installed extension, then opened IDE and attempted to add iPhone.

Says XCode not installed when it is

![CleanShot 2024-06-06 at 10 39 50](https://github.com/software-mansion/react-native-ide/assets/918740/cd448751-91f3-45cc-b1d8-c336727d2d95)

**Comment by jakub-gonet** [comment]
Do you use XCode beta? What's the output of `xcode-select -p`?

**Comment by jakub-gonet** [comment]
This issue was not active for some time so I'm closing it.
If you need further help please reply or create a new issue.
