### ISSUE TITLE
Add Iphone button is not working

### ISSUE THREAD

**Issue by chhatrapati295** [software-mansion/react-native-ide#359]
When i click on Add iphone button , it is not working , only loader moving & moving. Nothing happened. Please fix it.

**Comment by jakub-gonet** [comment]
Do you have installed xcode, xcode tools and pods in your project? Does it work without the React Native IDE? Can you please add logs from visual studio code? (Toggle Developer Tools in help menu).

**Comment by chhatrapati295** [comment]
No, xcode isn't installed. can we do without it ?

**Comment by jakub-gonet** [comment]
We plan to allow users to run their projects without leaving React Native IDE in the long term. This will replace current "IDE only should work if you can run the project without it"
In any case, having simulator and xcode tools installed is necessary to run ios apps and this can't really change.
