### ISSUE TITLE
extension update broke 

### ISSUE THREAD

**Issue by philipheinser** [software-mansion/react-native-ide#381]
it says check logs. logs appear empty. after update extension always get: 

<img width="1354" alt="Screenshot 2024-06-13 at 21 50 26" src="https://github.com/software-mansion/react-native-ide/assets/3705499/3fe02ce8-63d7-49dd-bdc8-dedd6d7ced98">

**Comment by kmagiera** [comment]
those are not logs of the extension. Can you try the instructions from here to see the extension logs: https://ide.swmansion.com/docs/troubleshooting#6-accessing-extension-logs 

Also you may want to try using clean rebuild option from the settings menu

**Comment by philipheinser** [comment]
@kmagiera it had an old simulator that was deleted selected that was the reason for the error I added a new one and deleted the old one. took a while to figure out.
