### ISSUE TITLE
Simulator view is missing after updating to 0.0.15

### ISSUE THREAD

**Issue by terrysahaidak** [software-mansion/react-native-ide#382]
**Description*
Just updated from 0.0.14 to 0.0.15 and the simulator view is missing:

<img width="1657" alt="image" src="https://github.com/software-mansion/react-native-ide/assets/7809008/76305b35-b063-4850-b8aa-fa7cf1597bc1">

I waited for some time and nothing appeared, I only saw flashes of a progress bar.

It's building the app in the background for sure since uses 100% CPU.

Also after killing VSCode the simulator server process still exists:

<img width="554" alt="image" src="https://github.com/software-mansion/react-native-ide/assets/7809008/902e1890-4167-4ff0-a9b5-3f1079f7d6ac">

**Environment**
- IDE: 0.0.15
- RN: 0.73.8

**Comment by kmagiera** [comment]
Thanks for reporting. Do you see anything in logs? Use command pallette and open "Developer: show logs" then select "React  Native IDE" from the dropdown.

Can you try deleting all versions of the extension under `~/.vscode/extensions/swmansion.react-native-ide-0.0.1*` ? Apparently when you uninstall extension VSCode doesn't delete that directory. After deleting try installing the extension again

**Comment by kmagiera** [comment]
sorry for the trouble, I think this just has to do with the change we made for the data format for the zoom feature. Can you just try changing the zoom level to fit?

**Comment by terrysahaidak** [comment]
oh yes i just noticed that my zoom after updating was 61x (i read it as 0.61), changing to the normal zoom fixed it, thanks!
