### ISSUE TITLE
Currently I can close the Simulator View with cmd+w (mac) accidentally.

### ISSUE THREAD

**Issue by lenarmazitov** [software-mansion/react-native-ide#387]
**Description**
Currently I can close the Simulator View with cmd+w (mac) accidentally. Sometimes you think that you have focused current tab with code but actually Simulator View tab was focused.
Maybe add some confirmation before close, or prevent closing the tab by hotkeys.

**Environment**
- Version of currently used React Native IDE: 0.0.15
- Version of React Native/Expo used in the project: No Matter

**Comment by kewinzaq1** [comment]
@lenarmazitov Hi I'm coming up with a solution. What do you think about it? https://github.com/software-mansion/react-native-ide/pull/390/files
