### ISSUE TITLE
Cannot run project

### ISSUE THREAD

**Issue by coderclub-team** [software-mansion/react-native-ide#410]
when i open React Native IDE in my vscode on macbook air m1, It shows an error like "Open build logs to find out what went wrong."

**Comment by filip131311** [comment]
Hello, thank you for the feedback,
would you mind providing logs for that error? 

You can also refer to our troubleshooting page: 
https://ide.swmansion.com/docs/troubleshooting

**Comment by jakub-gonet** [comment]
This issue was not active for some time so I'm closing it.
If you need further help please reply or create a new issue.
