### ISSUE TITLE
Getting Build Error of node_module custom lib png file

### ISSUE THREAD

**Issue by sunilyadavfabhotel** [software-mansion/react-native-ide#420]
**Description*
In build logs it says BUILD SUCCEEDED but the app has a png file error of our custom UI lib
<img width="584" alt="Screenshot 2024-07-03 at 6 13 23 PM" src="https://github.com/software-mansion/react-native-ide/assets/139126586/96743f7e-2205-47ac-a279-4d724a7637d8">

<img width="509" alt="Screenshot 2024-07-03 at 6 13 53 PM" src="https://github.com/software-mansion/react-native-ide/assets/139126586/a8deb598-81e7-4ada-a70f-63d7a62e8e14">

I have tried to add react-native.metro.js file in lib but its still not able to pick the assets of our lib and keep failing and saying build error and in debug terminal it say BUILD SUCCEEDED

**Comment by jakub-gonet** [comment]
Are you able to share your metro config here? We're overriding [some keys in there](https://github.com/software-mansion/react-native-ide/blob/88f4caa51da22199f023ab57f543d601af570649/packages/vscode-extension/lib/metro_helpers.js#L28), maybe you project's setting for assets gets dropped.

**Comment by sunilyadavfabhotel** [comment]
@jakub-gonet here is metro file,

const {getDefaultConfig, mergeConfig} = require('@react-native/metro-config');

const defaultConfig = getDefaultConfig(__dirname);

const {
  resolver: {sourceExts, assetExts},
} = getDefaultConfig(__dirname);

const config = {
  transformer: {
    getTransformOptions: async () => ({
      transform: {
        experimentalImportSupport: false,
        inlineRequires: true,
      },
    }),
    babelTransformerPath: require.resolve('react-native-svg-transformer'),
  },
  resolver: {
    assetExts: assetExts.filter(ext => ext !== 'svg'),
    sourceExts: [...sourceExts, 'svg'],
  },
};

module.exports = mergeConfig(defaultConfig, config);

**After the React Native update, and adding lib location in TS config file, its got fixed so closing this issue **
