### ISSUE TITLE
Java Process Duplication Issue in Vscode Extension Causing Battery Drain

### ISSUE THREAD

**Issue by Seeeeeck** [software-mansion/react-native-ide#459]
It seems like there's an issue with the Expo extension where Java processes are not closing when you reload or close the emulators, causing them to duplicate and leading to excessive battery usage on your MacBook. The idea is to ensure that when you close and restart an emulator, any associated Java processes are also terminated. This issue caused my MacBook's battery to drain completely in just 40 minutes while using 100% of its capacity.

**Comment by filip131311** [comment]
This, issue was inactive for 2 weeks. I'll close it for now if you have any more questions or information, please don't be afraid to write about it anyway.
