### ISSUE TITLE
[Sim Server] Video replays

### ISSUE THREAD

**Issue by darthez** [software-mansion/react-native-ide#460]
save X seconds of the past video stream to file as mp4

**Comment by balins** [comment]
# Description

## Goals
- Allow user to save last `N` seconds of simulator/emulator stream to an MP4 file (the user will be able to trigger it from UI)
- Allow user to view the MP4 file in the IDE
- Allow the buffer size (`N`) to be configurable when starting the simulator server, ideally it should be configurable in runtime

## Requirements
- The MP4 file should be served by the simulator server's HTTP server (we're not sure we can access the filesystem from the extension)
- Try to minimize the performance impact of dumping and rotating JPEG frames

## Solution
- store encoded JPEG frames on the filesystem (10s of 60FPS MJPEG video would take up about 1.5GB of RAM, so we can't store the in-memory)
- store information about frame timestamp so we can generate PTS in the encoded H264
- rotate frames to account for last `N` seconds of simulator/emulator stream, so we don't run out of disk space
- when receiving `videoSnapshot` command from the IDE, encode the frames as H264, mux it into an MP4 file and serve from the HTTP server at `/snapshot.mp4` (need to figure out how to notify the IDE that the snapshot is ready)
