### ISSUE TITLE
Infinit loading and device not shown

### ISSUE THREAD

**Issue by gezimgg** [software-mansion/react-native-ide#465]
**Description*
When I got the extension for the first time, everything went well. After a few days, this issue occurred without any error.

**Environment**
Version of currently used React Native IDE (Extensions tab -> click on React Native IDE extension -> version is located next to the extension name)
### React Native IDE v0.0.16

Version of React Native/Expo used in the project.
### "react-native": "0.73.1"

Log:

-The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 12.0 to 18.0.99. (in target 'FirebaseInstallations-FirebaseInstallations_Privacy' from project 'Pods')

### Selected: iPhone 15 Pro iOS 17.5

<img width="717" alt="image" src="https://github.com/user-attachments/assets/b35003f5-2428-4cb8-b1a0-fd19e41f8513">

**Comment by jakub-gonet** [comment]
What happens if you reset the zoom level to 1x?

**Comment by gezimgg** [comment]
@jakub-gonet what a hack, now with zoom level to 1x it works, thanks a lot!
