### ISSUE TITLE
Support for windows 64 bit

### ISSUE THREAD

**Issue by adrielgama** [software-mansion/react-native-ide#501]
**Description**
> The 'React Native IDE' extension is not available in Visual Studio Code for Windows 64 bit.

When trying to install the extension directly in VSCode, it says that it only supports macOS, and other versions do not support Windows 64-bit.

Is there any way to solve this problem?

**Comment by filip131311** [comment]
Hello, thank you for taking the time to write to us, I am glad to inform you that the next version is going to support windows, We are currently in a testing stage for that reale.

**Comment by balins** [comment]
@adrielgama @ki11qwerty @dpadula We've added experimental Windows support in release [v0.0.18-beta](https://github.com/software-mansion/react-native-ide/releases/tag/v0.0.18-beta) 🎉
